export const callType = {
  AUDIO_PERSONAL_CODE: "AUDIO_PERSONAL_CODE",
  VIDEO_PERSONAL_CODE: "VIDEO_PERSONAL_CODE",
};

export const preOfferAnswer = {
  CALLEE_NOT_FOUND: "CALLEE_NOT_FOUND",
  CALL_ACCEPTED: "CALL_ACCEPTED",
  CALL_REJECTED: "CALL_REJECTED",
  CALL_UNAVAILABLE: "CALL_UNAVAILABLE",
};

export const webRTCSignaling = {
  OFFER: "OFFER",
  ANSWER: "ANSWER",
  ICE_CANDIDATE: "ICE_CANDIDATE",
};

export const callState = {
  CALL_AVAILABLE: "CALL_AVAILABLE",
  CALL_UNAVAILABLE: "CALL_UNAVAILABLE",
  CALL_AVAILABLE_ONLY_AUDIO: "CALL_AVAILABLE_ONLY_AUDIO",
};

export const dialogTypes = {
  CALLER_DIALOG: "CALLER_DIALOG",
  CALLEE_DIALOG: "CALLEE_DIALOG",
  CALLER_REJECTION_DIALOG: "CALLER_REJECTION_DIALOG",
};

export const recordingState = {
  RECORDING: "RECORDING",
  PAUSED: "PAUSED",
  RESUMED: "RESUMED",
  INACTIVE: "STOPPED"
};
